name: Release CI
on:
  repository_dispatch:

  workflow_dispatch:

  pull_request:
    types:
      - closed
    paths-ignore:
      - 'apps/**'
      - '**/*.md'

  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'apps/**'
  #     - '**/*.md'
env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm store and .node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-pnpm-store-cache

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test

  release:
    needs: test
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@${{ github.repository_owner }}'

      - name: Install dependencies
        run: pnpm install

      - name: Cache pnpm store and .node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-pnpm-store-cache

      - name: Build
        run: pnpm run build

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Publish to GitHub Package Registry
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ env.GITHUB_TOKEN }}

  clean:
    needs: Release
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
          token: ${{ env.GITHUB_TOKEN }}

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 1
          delete_tags: true
